name: Release

on:

  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  release-please:

    permissions:
      contents: write
      pull-requests: write

    runs-on: ubuntu-latest

    steps:

      - name: Run Release Please
        uses: googleapis/release-please-action@7987652d64b4581673a76e33ad5e98e3dd56832f # v4.1.3
        id: r
